name: core
description: "core"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  product:
    path: ../product
  cupertino_icons: ^1.0.6
  core_libs:
    path: ../../packages/core_libs
  go_router: ^14.0.2
  core_ui:
    path: ../../packages/core_ui


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: SugarCream
      fonts:
        - asset: assets/fonts/SugarCream.otf
          weight: 200
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
          weight: 100